# Site settings
title:Jake Mingolla Portfolio
email:jakemingolla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site

twitter_username:
github_username:jakemingolla

# Build settings
markdown: kramdown
